Fix GARCH11: missing [] in tt.concatenate()
This will prevent the error:
```
TypeError: ("The 'tensors' argument must be either a tuple or a list, make sure you did not forget () or [] around arguments of concatenate.", sigma0)```